![](https://api.brandy.run/core/core-logo-wide)

# Map, Filter, Reduce

## 1. Callback

Hemos visto que un patrón muy utilizado en la programación funcional es el patrón callback, donde una función es pasada como argumento de una otra función.

Existen 3 operaciones muy importantes que utilizan de ese patrón en una serie de lenguajes de programación y herramientas, incluso, por supuesto, en python.

La estructura de la utilización de esas funciones es muy parecida, pero sus funcionalidades son muy diferentes.

![](img/functions.png)

## 2. Map

La primera de las 3 operaciones que veremos es el map. La función `map` recibe 2 parámetros: un array y otra función. La función se ejecutará con cada elemento del array como argumento (mapeo) y el array resultante será devuelto como resultado del map.

![](img/map.png)

In [1]:
import numpy as np

In [2]:
lst = np.random.randint(1,101, 30)

In [3]:
lst

array([81, 54, 62,  1, 92, 10, 10, 58, 40, 39, 19,  8, 58, 41, 20, 13,  4,
       85, 71, 40, 53,  2, 94, 54, 37, 38,  8, 55, 11, 12])

In [4]:
def mitad(a):
    return a/2

Como podemos ver, la función `map` devuelve un objeto del tipo `map`, que como podemos imaginar por la primera parte de la lección, es un objeto iterador. Si lo convertimos a una lista, podemos ver los resultados.

In [5]:
map(mitad, lst)

Muy comunmente, para aprovechar de el patrón callback, usaremos la función map con una función lambda.

In [6]:
len(list(map(lambda x: x*2, lst)))

30

In [7]:
list(map(mitad, lst))

[40.5,
 27.0,
 31.0,
 0.5,
 46.0,
 5.0,
 5.0,
 29.0,
 20.0,
 19.5,
 9.5,
 4.0,
 29.0,
 20.5,
 10.0,
 6.5,
 2.0,
 42.5,
 35.5,
 20.0,
 26.5,
 1.0,
 47.0,
 27.0,
 18.5,
 19.0,
 4.0,
 27.5,
 5.5,
 6.0]

El mapping es equivalente a hacer lo mismo en un list comprehension, con la diferencia de que genera un objeto iterador en lugar de una lista.

## 3. Filter

Igualmente, tenemos la función filter, que también tiene su equivalente en el formato list comprehension. Hay una particularidad de la función que le pasemos a filter: los outputs de esa función deben ser equivalentes a `True` y `False`. Al ejecutar esa función con cada elemento del array como input, los que se consideren `True` estarán presentes en el resultado final, mientras los considerados `False` no estarán.

Como se trata de un filtrado, el array resultante tendrá longitud entre 0 y la longitud de el array original

![](img/filter.png)

In [8]:
lst

array([81, 54, 62,  1, 92, 10, 10, 58, 40, 39, 19,  8, 58, 41, 20, 13,  4,
       85, 71, 40, 53,  2, 94, 54, 37, 38,  8, 55, 11, 12])

In [9]:
list(filter(lambda x: x%3 == 0, lst))

[81, 54, 39, 54, 12]

In [10]:
lst

array([81, 54, 62,  1, 92, 10, 10, 58, 40, 39, 19,  8, 58, 41, 20, 13,  4,
       85, 71, 40, 53,  2, 94, 54, 37, 38,  8, 55, 11, 12])

Igualmente, la función filter devuelve un iterador.

In [11]:
filter(lambda x: x%3 == 0, lst)

## 4. Reduce

La tercera de esas funciones que se aprovechan de el patrón callback es la función reduce, la más diferente entre las 3. En lugar de devolver un array, la función reduce devuelve un único valor.

El proceso para calcular ese valor final es aplicar la función a los 2 primeros elementos del array. El resultado vuelve a passarse a la función, con el siguiente de los elementos, y así sucesivamente hasta llegar al último elemento y el resultado final.

Por ese motivo, al contrário de las dos herramientas anteriores, la función que pasemos al `reduce` debe recibir 2 parámetros.

![](img/reduce.png)

In [12]:
from functools import reduce

In [13]:
reduce(lambda x,y:x if x>y else y, lst)

94

In [14]:
lst

array([81, 54, 62,  1, 92, 10, 10, 58, 40, 39, 19,  8, 58, 41, 20, 13,  4,
       85, 71, 40, 53,  2, 94, 54, 37, 38,  8, 55, 11, 12])

In [15]:
max(lst)

94

Hay un tercer parámetro opcional que podemos utilizar en el `reduce`, que es el parámetro `initializer`. Caso queramos que el primer parámetro de la primera llamada a la función sea un otro valor que no el primer elemento del array.

In [16]:
reduce(lambda x,y:x if x>y else y, lst, 99999)

99999

In [17]:
list(lst).insert(0,9999)

In [18]:
lst

array([81, 54, 62,  1, 92, 10, 10, 58, 40, 39, 19,  8, 58, 41, 20, 13,  4,
       85, 71, 40, 53,  2, 94, 54, 37, 38,  8, 55, 11, 12])

In [19]:
lst = [i for i in lst]

In [20]:
reduce(lambda x,y:x if x>y else y, lst)

94

In [21]:
reduce(lambda x,y:x if x>y else y,list("holasdoiwqdioauofalwkdijkalosiuaouosd"))

'w'