![](https://api.brandy.run/core/core-logo-wide)

# Exercise: Map, Filter, Reduce

## Ejercicio 1: Transform Authors' names

<img src="img/books.png" width="200">

En el esfuerzo de mejor organizar una libreria, su mantenedor decide cambiar el orden en que los libros están dispuestos. Hasta el momento se hacia el orden alfabético por `"Nombre Apellido_1 Apellido_2"` de cada autor. Ahora se ha eligido tenerles en el siguiente formato `"{APELLIDO_2}, {Nombre} {Apellido_1}"`. ¿Puedes hacerlo utilizando las herramientas que conoces para toda esa lista de autores?

Hay authores con menos o más de 2 palabras en sus apellidos, o nombre compuesto. En todos los casos, la última palabra deve ser la trasladada al princípio y capitalizada.

Ej.:
```
Federico Garcia Lorca ---> LORCA, Federico Garcia
Franz Kafka           ---> KAFKA, Franz
```

In [1]:
authors = ['Agatha Christie', 'Benito Pérez Galdós', 'Calderón de la Barca', 'Charles Dickens', 
           'Clarice Lispector', 'Dante Alighieri', 'Edgar Allan Poe', 'Federico Garcia Lorca', 
           'Fernando Pessoa', 'Franz Kafka', 'Fyodor Dostoyevsky', 'Gabriel García Márquez', 
           'George Orwell', 'Herman Melville', 'Hermann Hesse', 'James Joyce', 'Jane Austen', 
           'Johann Wolfgang von Goethe', 'Julio Cortázar', 'Lewis Carroll', 'Marcel Proust', 
           'Mario Vargas Llosa', 'Miguel de Cervantes', 'Ortega y Gasset', 'Oscar Wilde', 
           'Pablo Neruda', 'Pío Baroja', 'Ramón María del Valle-Inclán', 'Victor Hugo', 
           'Virginia Woolf', 'William Shakespeare']

In [2]:
'Agatha Christie'
'Calderón de la Barca'

'Calderón de la Barca'

In [3]:
def modificacion_nombre(nombre):
    lst = nombre.split()
    return f"{lst[-1].upper()}, {' '.join(lst[:-1])}"

In [4]:
modificacion_nombre('Agatha Christie')

'CHRISTIE, Agatha'

In [5]:
list(map(modificacion_nombre, authors))

['CHRISTIE, Agatha',
 'GALDÓS, Benito Pérez',
 'BARCA, Calderón de la',
 'DICKENS, Charles',
 'LISPECTOR, Clarice',
 'ALIGHIERI, Dante',
 'POE, Edgar Allan',
 'LORCA, Federico Garcia',
 'PESSOA, Fernando',
 'KAFKA, Franz',
 'DOSTOYEVSKY, Fyodor',
 'MÁRQUEZ, Gabriel García',
 'ORWELL, George',
 'MELVILLE, Herman',
 'HESSE, Hermann',
 'JOYCE, James',
 'AUSTEN, Jane',
 'GOETHE, Johann Wolfgang von',
 'CORTÁZAR, Julio',
 'CARROLL, Lewis',
 'PROUST, Marcel',
 'LLOSA, Mario Vargas',
 'CERVANTES, Miguel de',
 'GASSET, Ortega y',
 'WILDE, Oscar',
 'NERUDA, Pablo',
 'BAROJA, Pío',
 'VALLE-INCLÁN, Ramón María del',
 'HUGO, Victor',
 'WOOLF, Virginia',
 'SHAKESPEARE, William']

## Ejercicio 2: Temperature conversion

<img src="img/temp.jpeg" width="200">

En una estación meteorológica se coletan datos de las temperaturas (máxima y mínima) al largo de un año. Esos datos serán entregados a un grupo de científicos, pero tienen que ser convertidos a °C, una vez que fueron medidos en °F.

In [6]:
max_min_temp = [(24,8),(29,13),(41,24),(58,37),(69,49),(79,59),
                (83,64),(81,62),(72,52),(58,40),(41,26),(27,12)]

In [7]:
# -32 * 5/9

In [8]:
t = ("Madrid",19,"Antonio")

In [9]:
Ciudad, edad, nombre = t

In [10]:
print( Ciudad, edad, nombre,)

Madrid 19 Antonio


In [11]:
agrupacion = Ciudad, edad, nombre, "España"

In [12]:
agrupacion

('Madrid', 19, 'Antonio', 'España')

In [13]:
def convert_to_c(max_min):
    maxima, minima = max_min
    maxima = (maxima - 32) * 5/9
    minima = (minima - 32) * 5/9
    return maxima,minima

In [14]:
def convert_to_c(max_min):
    return (max_min[0] - 32) * 5/9, (max_min[1] - 32) * 5/9

In [15]:
convert_to_c((24,8))

(-4.444444444444445, -13.333333333333334)

In [16]:
list(map(convert_to_c, max_min_temp))

[(-4.444444444444445, -13.333333333333334),
 (-1.6666666666666667, -10.555555555555555),
 (5.0, -4.444444444444445),
 (14.444444444444445, 2.7777777777777777),
 (20.555555555555557, 9.444444444444445),
 (26.11111111111111, 15.0),
 (28.333333333333332, 17.77777777777778),
 (27.22222222222222, 16.666666666666668),
 (22.22222222222222, 11.11111111111111),
 (14.444444444444445, 4.444444444444445),
 (5.0, -3.3333333333333335),
 (-2.7777777777777777, -11.11111111111111)]

## Ejercicio 3: Circle areas

<img src="img/circle.jpeg" width="200">

A partir del `range(1,101)`, calcula el área de circulos con radio igual a cada uno de los elementos de ese range.

In [17]:
from math import pi

In [18]:
# pi * r**2

In [19]:
def area(r):
    return pi * (r**2)

In [20]:
area(3)

28.274333882308138

In [21]:
list(map(area, range(1,101)))[:5]

[3.141592653589793,
 12.566370614359172,
 28.274333882308138,
 50.26548245743669,
 78.53981633974483]

In [22]:
list(map(lambda r: pi * (r**2), range(1,101)))[:5]

[3.141592653589793,
 12.566370614359172,
 28.274333882308138,
 50.26548245743669,
 78.53981633974483]

## Ejercicio 4: Sorting Sorteds

Filtra la lista de listas abajo para incluir solo las listas en que los 3 elementos estén ordenados ascendientemente.

In [23]:
import numpy as np
lst = np.random.randint(1,101,(100,3))

In [24]:
lst[:5]

array([[66, 80, 99],
       [69, 53, 27],
       [ 2,  3, 38],
       [37, 22, 98],
       [38, 98, 76]])

In [25]:
[1,2,3,4,5]*5

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [26]:
np.array([1,2,3,4,5])*5

array([ 5, 10, 15, 20, 25])

In [27]:
def ordenados(lista):
    if all(lista==sorted(lista)):
        return True
    else:
        return False

In [28]:
ordenados(np.array([6, 27, 92]))

True

In [29]:
list(filter(ordenados, lst))

[array([66, 80, 99]),
 array([ 2,  3, 38]),
 array([29, 88, 89]),
 array([ 5, 21, 61]),
 array([ 6, 31, 44]),
 array([ 9, 10, 74]),
 array([22, 24, 82]),
 array([21, 54, 58]),
 array([ 2, 42, 57]),
 array([25, 31, 70]),
 array([ 2, 62, 94]),
 array([66, 80, 86]),
 array([ 8, 37, 71]),
 array([26, 33, 95]),
 array([ 8, 28, 82]),
 array([25, 43, 60]),
 array([ 3, 39, 94])]

In [30]:
list(filter(lambda x: x[0] <= x[1] and x[1] <= x[2], lst))

[array([66, 80, 99]),
 array([ 2,  3, 38]),
 array([29, 88, 89]),
 array([ 5, 21, 61]),
 array([ 6, 31, 44]),
 array([ 9, 10, 74]),
 array([22, 24, 82]),
 array([21, 54, 58]),
 array([ 2, 42, 57]),
 array([25, 31, 70]),
 array([ 2, 62, 94]),
 array([66, 80, 86]),
 array([ 8, 37, 71]),
 array([26, 33, 95]),
 array([ 8, 28, 82]),
 array([25, 43, 60]),
 array([ 3, 39, 94])]

## Ejercicio 5: Letter order

<img src="img/letters.jpeg" width="200">

Recentemente has encontrado la lista abajo que contiene las 100 palabras más utilizadas en el inglés. Decides investigar algunas cosas sobre esa lista.
- Primero, separa solo las palabras que poséen por lo menos 2 vocales.
- De el listaje anterior, elimina cualquier palabra cuyas vocales no estén en el orden alfabético

In [31]:
words = ["a","ability","able","about","above","accept","according","account","across","act","action","activity","actually","add","address","administration","admit","adult","affect","after","again","against","age","agency","agent","ago","agree","agreement","ahead","air","all","allow","almost","alone","along","already","also","although","always","American","among","amount","analysis","and","animal","another","answer","any","anyone","anything","appear","apply","approach","area","argue","arm","around","arrive","art","article","artist","as","ask","assume","at","attack","attention","attorney","audience","author","authority","available","avoid","away","baby","back","bad","bag","ball","bank","bar","base","be","beat","beautiful","because","become","bed","before","begin","behavior","behind","believe","benefit","best","better","between","beyond","big","bill","billion","bit","black","blood","blue","board","body","book","born","both","box","boy","break","bring","brother","budget","build","building","business","but","buy","by","call","camera","campaign","can","cancer","candidate","capital","car","card","care","career","carry","case","catch","cause","cell","center","central","century","certain","certainly","chair","challenge","chance","change","character","charge","check","child","choice","choose","church","citizen","city","civil","claim","class","clear","clearly","close","coach","cold","collection","college","color","come","commercial","common","community","company","compare","computer","concern","condition","conference","Congress","consider","consumer","contain","continue","control","cost","could","country","couple","course","court","cover","create","crime","cultural","culture","cup","current","customer","cut","dark","data","daughter","day","dead","deal","death","debate","decade","decide","decision","deep","defense","degree","Democrat","democratic","describe","design","despite","detail","determine","develop","development","die","difference","different","difficult","dinner","direction","director","discover","discuss","discussion","disease","do","doctor","dog","door","down","draw","dream","drive","drop","drug","during","each","early","east","easy","eat","economic","economy","edge","education","effect","effort","eight","either","election","else","employee","end","energy","enjoy","enough","enter","entire","environment","environmental","especially","establish","even","evening","event","ever","every","everybody","everyone","everything","evidence","exactly","example","executive","exist","expect","experience","expert","explain","eye","face","fact","factor","fail","fall","family","far","fast","father","fear","federal","feel","feeling","few","field","fight","figure","fill","film","final","finally","financial","find","fine","finger","finish","fire","firm","first","fish","five","floor","fly","focus","follow","food","foot","for","force","foreign","forget","form","former","forward","four","free","friend","from","front","full","fund","future","game","garden","gas","general","generation","get","girl","give","glass","go","goal","good","government","great","green","ground","group","grow","growth","guess","gun","guy","hair","half","hand","hang","happen","happy","hard","have","he","head","health","hear","heart","heat","heavy","help","her","here","herself","high","him","himself","his","history","hit","hold","home","hope","hospital","hot","hotel","hour","house","how","however","huge","human","hundred","husband","I","idea","identify","if","image","imagine","impact","important","improve","in","include","including","increase","indeed","indicate","individual","industry","information","inside","instead","institution","interest","interesting","international","interview","into","investment","involve","issue","it","item","its","itself","job","join","just","keep","key","kid","kill","kind","kitchen","know","knowledge","land","language","large","last","late","later","laugh","law","lawyer","lay","lead","leader","learn","least","leave","left","leg","legal","less","let","letter","level","lie","life","light","like","likely","line","list","listen","little","live","local","long","look","lose","loss","lot","love","low","machine","magazine","main","maintain","major","majority","make","man","manage","management","manager","many","market","marriage","material","matter","may","maybe","me","mean","measure","media","medical","meet","meeting","member","memory","mention","message","method","middle","might","military","million","mind","minute","miss","mission","model","modern","moment","money","month","more","morning","most","mother","mouth","move","movement","movie","Mr","Mrs","much","music","must","my","myself","name","nation","national","natural","nature","near","nearly","necessary","need","network","never","new","news","newspaper","next","nice","night","no","none","nor","north","not","note","nothing","notice","now","n't","number","occur","of","off","offer","office","officer","official","often","oh","oil","ok","old","on","once","one","only","onto","open","operation","opportunity","option","or","order","organization","other","others","our","out","outside","over","own","owner","page","pain","painting","paper","parent","part","participant","particular","particularly","partner","party","pass","past","patient","pattern","pay","peace","people","per","perform","performance","perhaps","period","person","personal","phone","physical","pick","picture","piece","place","plan","plant","play","player","PM","point","police","policy","political","politics","poor","popular","population","position","positive","possible","power","practice","prepare","present","president","pressure","pretty","prevent","price","private","probably","problem","process","produce","product","production","professional","professor","program","project","property","protect","prove","provide","public","pull","purpose","push","put","quality","question","quickly","quite","race","radio","raise","range","rate","rather","reach","read","ready","real","reality","realize","really","reason","receive","recent","recently","recognize","record","red","reduce","reflect","region","relate","relationship","religious","remain","remember","remove","report","represent","Republican","require","research","resource","respond","response","responsibility","rest","result","return","reveal","rich","right","rise","risk","road","rock","role","room","rule","run","safe","same","save","say","scene","school","science","scientist","score","sea","season","seat","second","section","security","see","seek","seem","sell","send","senior","sense","series","serious","serve","service","set","seven","several","sex","sexual","shake","share","she","shoot","short","shot","should","shoulder","show","side","sign","significant","similar","simple","simply","since","sing","single","sister","sit","site","situation","six","size","skill","skin","small","smile","so","social","society","soldier","some","somebody","someone","something","sometimes","son","song","soon","sort","sound","source","south","southern","space","speak","special","specific","speech","spend","sport","spring","staff","stage","stand","standard","star","start","state","statement","station","stay","step","still","stock","stop","store","story","strategy","street","strong","structure","student","study","stuff","style","subject","success","successful","such","suddenly","suffer","suggest","summer","support","sure","surface","system","table","take","talk","task","tax","teach","teacher","team","technology","television","tell","ten","tend","term","test","than","thank","that","the","their","them","themselves","then","theory","there","these","they","thing","think","third","this","those","though","thought","thousand","threat","three","through","throughout","throw","thus","time","to","today","together","tonight","too","top","total","tough","toward","town","trade","traditional","training","travel","treat","treatment","tree","trial","trip","trouble","true","truth","try","turn","TV","two","type","under","understand","unit","until","up","upon","us","use","usually","value","various","very","victim","view","violence","visit","voice","vote","wait","walk","wall","want","war","watch","water","way","we","weapon","wear","week","weight","well","west","western","what","whatever","when","where","whether","which","while","white","who","whole","whom","whose","why","wide","wife","will","win","wind","window","wish","with","within","without","woman","wonder","word","work","worker","world","worry","would","write","writer","wrong","yard","yeah","year","yes","yet","you","young","your","yourself"]

In [32]:
def at_leats_two_vocals(word):
    vocals = "aeiou"
    vocals_found = 0
    for vocal in vocals:
        if word.count(vocal) > 0:
            #print(vocal)
            vocals_found += 1
    if vocals_found > 1:
        return True
    else:
        return False
    

In [33]:
at_leats_two_vocals("ability")

True

In [34]:
primera_parte = list(filter(at_leats_two_vocals, words))

In [35]:
primera_parte[:10]

['ability',
 'able',
 'about',
 'above',
 'accept',
 'according',
 'account',
 'across',
 'action',
 'activity']

In [36]:
def alpha_order(word):
    vocales = "aeiou"
    res = ""
    for character in word:
        if character in vocales:
            res+=character
    #print(res, "".join(sorted(res)))
    if res == "".join(sorted(res)):
        return True
    else:
        return False

In [37]:
word = "administration"

In [38]:
alpha_order(word)

False

In [39]:
final = list(filter(alpha_order, primera_parte))

In [40]:
final[:10]

['ability',
 'able',
 'about',
 'accept',
 'account',
 'across',
 'action',
 'activity',
 'address',
 'admit']

## Ejercicio 6 (Bonus): Code your own `map` `filter` and `reduce` implementations. 

<img src="img/higher_order.jpeg" width="400">

Hemos utilizado las funciones `map`, `filter` y `reduce` en los ejercícios anteriores. ¿Serías capaz de implementarlas si no existieran?
En ese ejercício debes definir las 3 funciones `my_map`, `my_filter` y `my_reduce`.

In [41]:
def my_map(func, arr):
    res = []
    for el in arr:
        res.append(func(el))
    return res
        
def my_filter(func, arr):
    res = []
    for el in arr:
        if func(el):
            res.append(el)
    return res

def my_reduce(func, arr, initiallizer):
    resultado = initiallizer
    segundo = arr[0]
    arr = arr[1:]
    resultado = func(resultado, segundo)
    for el in arr:
        resultado = func(resultado, el)
    return resultado

In [42]:
my_map(lambda r: pi * (r**2), range(1,101))[:5]

[3.141592653589793,
 12.566370614359172,
 28.274333882308138,
 50.26548245743669,
 78.53981633974483]

In [43]:
f2 = my_filter(alpha_order, primera_parte)

In [44]:
final == f2

True

In [45]:
from functools import reduce

In [46]:
reduce(lambda p,s:p if p>s else s, [1,2,4,1,12,3,5,6,21,4,2,3,5], 40)

40

In [47]:
my_reduce(lambda p,s:p if p>s else s, [1,2,4,1,12,3,5,6,21,4,2,3,5], 40)

40

## Ejercicio 7 (Bonus): Fibonacci HARD 🔥

Solo con `reduce` y un `lambda`, ¿puedes producir la secuencia de Fibonacci?

- https://en.wikipedia.org/wiki/Fibonacci_number

In [48]:
[1,2]+[3]+[6]

[1, 2, 3, 6]

In [49]:
sum([1,2])

3

In [50]:
reduce(lambda arr, _ : arr + [ sum(arr[-2:]) ], range(11), [0,1])

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144]